apiVersion: apps/v1
kind: Deployment
metadata:
  name: orquestrador-java-21
  namespace: projetos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orquestrador-java-21
  template:
    metadata:
      labels:
        app: orquestrador-java-21
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/service: orquestrador-graalvm
        tags.datadoghq.com/version: "1.0.0"
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: orquestrador-java-21
          image: localhost:5000/orquestrador.java.21:1.0.7
          ports:
            - containerPort: 8080
          env:
            - name: DD_ENV
              value: prod
            - name: DD_SERVICE
              value: orquestrador-graalvm
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_AGENT_HOST
              value: datadog.datadog.svc.cluster.local
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_ENABLED
              value: "true"
