apiVersion: apps/v1
kind: Deployment
metadata:
  name: orquestrador-java-21
  namespace: projetos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orquestrador-java-21
  template:
    metadata:
      labels:
        app: orquestrador-java-21
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/service: orquestrador-graalvm
        tags.datadoghq.com/version: "1.0.0"
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: orquestrador-java-21
          image: localhost:5000/orquestrador.java.21:1.0.11
          ports:
            - containerPort: 8080
          env:
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secret
                  key: api-key
            - name: DATADOG_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secret
                  key: app-key
